// Mock data for El Papu Store

const PRODUCTS = [
  {
    id: 1,
    nombre: "Auriculares Urban Bass Pro",
    categoria: "Tecnología",
    precio: 38990,
    precioAnterior: 54990,
    badge: "viral",
    descripcion: "Sonido potente, graves profundos y diseño urbano para llevar tu música a otro nivel.",
    caracteristicas: ["Bluetooth 5.3", "Hasta 40h de batería", "Cancelación de ruido activa", "Estuche premium incluido"],
    rating: 4.8,
    reviews: 312,
    stock: 23,
    color: "from-emerald-500/20 to-black",
    img: "https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 2,
    nombre: "Mini Parlante Neon Street",
    categoria: "Tecnología",
    precio: 19990,
    precioAnterior: 26990,
    badge: "oferta",
    descripcion: "Compacto, potente y con luces RGB. La banda sonora de la calle.",
    caracteristicas: ["10W RMS", "Resistente al agua IPX6", "Luces RGB sincronizadas", "Hasta 12h de uso"],
    rating: 4.6,
    reviews: 187,
    stock: 41,
    color: "from-lime-500/20 to-black",
    img: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 3,
    nombre: "Smartwatch Papu Fit",
    categoria: "Tecnología",
    precio: 44990,
    precioAnterior: null,
    badge: "nuevo",
    descripcion: "Tu día, tu deporte y tu estilo, todo en una pantalla AMOLED nítida.",
    caracteristicas: ["Pantalla AMOLED 1.85\"", "GPS integrado", "Monitor cardíaco 24/7", "Resistente al agua 5ATM"],
    rating: 4.7,
    reviews: 92,
    stock: 18,
    color: "from-teal-500/20 to-black",
    img: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 4,
    nombre: "Teclado Gamer RGB Compact",
    categoria: "Gaming",
    precio: 52990,
    precioAnterior: 69990,
    badge: "top",
    descripcion: "Switches mecánicos, RGB por tecla y formato compacto para setups urbanos.",
    caracteristicas: ["Switches mecánicos red", "Formato TKL 87 teclas", "RGB por tecla", "Cable trenzado removible"],
    rating: 4.9,
    reviews: 421,
    stock: 12,
    color: "from-green-500/30 to-black",
    img: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 5,
    nombre: "Mouse Gamer Glow",
    categoria: "Gaming",
    precio: 24990,
    precioAnterior: 32990,
    badge: "viral",
    descripcion: "Sensor de alta precisión y diseño ergonómico con glow verde neón.",
    caracteristicas: ["Sensor 16000 DPI", "7 botones programables", "Glow RGB ajustable", "Cable paracord ultraligero"],
    rating: 4.7,
    reviews: 256,
    stock: 34,
    color: "from-emerald-500/25 to-black",
    img: "https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 6,
    nombre: "Mochila Urbana Black",
    categoria: "Moda",
    precio: 34990,
    precioAnterior: null,
    badge: "nuevo",
    descripcion: "Resistente, espaciosa y con compartimento acolchado para tu setup.",
    caracteristicas: ["Capacidad 28L", "Compartimento laptop 15.6\"", "USB de carga externa", "Material impermeable"],
    rating: 4.5,
    reviews: 78,
    stock: 27,
    color: "from-zinc-700/40 to-black",
    img: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 7,
    nombre: "Gorra Street Edition",
    categoria: "Moda",
    precio: 14990,
    precioAnterior: 18990,
    badge: "oferta",
    descripcion: "Bordado relieve, visera plana y el estilo que estabas buscando.",
    caracteristicas: ["100% algodón premium", "Ajuste snapback", "Bordado relieve", "Edición limitada"],
    rating: 4.6,
    reviews: 134,
    stock: 56,
    color: "from-neutral-700/40 to-black",
    img: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 8,
    nombre: "Cargador Rápido Turbo 65W",
    categoria: "Accesorios",
    precio: 16990,
    precioAnterior: 22990,
    badge: "top",
    descripcion: "Carga ultrarrápida con triple puerto y protección inteligente.",
    caracteristicas: ["65W PD", "3 puertos USB-C / USB-A", "Protección cortocircuito", "Tamaño compacto"],
    rating: 4.8,
    reviews: 203,
    stock: 62,
    color: "from-emerald-600/20 to-black",
    img: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 9,
    nombre: "Soporte Celular Pro",
    categoria: "Accesorios",
    precio: 8990,
    precioAnterior: null,
    badge: "nuevo",
    descripcion: "Aluminio, ajustable y firme. Para escritorio o para grabar contenido.",
    caracteristicas: ["Aluminio anodizado", "Ángulo regulable 360°", "Base antideslizante", "Plegable"],
    rating: 4.4,
    reviews: 47,
    stock: 88,
    color: "from-zinc-600/30 to-black",
    img: "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 10,
    nombre: "Luces LED Setup 5m",
    categoria: "Hogar",
    precio: 12990,
    precioAnterior: 17990,
    badge: "viral",
    descripcion: "Personalizá tu cuarto o setup con luces sincronizadas por app.",
    caracteristicas: ["5m de tira RGB", "App con escenas", "Sincronización musical", "Adhesivo reforzado"],
    rating: 4.5,
    reviews: 311,
    stock: 49,
    color: "from-emerald-500/20 to-black",
    img: "https://images.unsplash.com/photo-1565183997392-2f6f122e5912?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 11,
    nombre: "Botella Térmica Dark 750ml",
    categoria: "Hogar",
    precio: 11990,
    precioAnterior: null,
    badge: "top",
    descripcion: "Mantiene frío 24h y caliente 12h. Acero premium con acabado mate.",
    caracteristicas: ["Capacidad 750ml", "Doble pared acero", "Boquilla deportiva", "Libre de BPA"],
    rating: 4.7,
    reviews: 167,
    stock: 73,
    color: "from-neutral-700/40 to-black",
    img: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 12,
    nombre: "Riñonera Urban Style",
    categoria: "Moda",
    precio: 13990,
    precioAnterior: 18990,
    badge: "oferta",
    descripcion: "Cruzada, cómoda y con todos los compartimentos que te faltaban.",
    caracteristicas: ["Material reforzado", "Múltiples compartimentos", "Correa ajustable", "Cierre antirobo"],
    rating: 4.5,
    reviews: 92,
    stock: 38,
    color: "from-zinc-700/40 to-black",
    img: "https://images.unsplash.com/photo-1591561954557-26941169b49e?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 13,
    nombre: "Webcam HD Stream 1080p",
    categoria: "Gaming",
    precio: 29990,
    precioAnterior: null,
    badge: "nuevo",
    descripcion: "Calidad 1080p, autofoco y micrófono integrado para streamers.",
    caracteristicas: ["1080p 60fps", "Autofoco rápido", "Micrófono dual", "Trípode incluido"],
    rating: 4.6,
    reviews: 41,
    stock: 22,
    color: "from-emerald-500/20 to-black",
    img: "https://images.unsplash.com/photo-1587202372616-b43abea06c2a?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 14,
    nombre: "Lentes Black Edition",
    categoria: "Moda",
    precio: 18990,
    precioAnterior: null,
    badge: "nuevo",
    descripcion: "Diseño urbano, filtro UV400 y estuche premium incluido.",
    caracteristicas: ["UV400", "Marco TR90", "Lente polarizada", "Estuche rígido"],
    rating: 4.7,
    reviews: 56,
    stock: 31,
    color: "from-neutral-700/40 to-black",
    img: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 15,
    nombre: "Power Bank Slim 20.000mAh",
    categoria: "Tecnología",
    precio: 22990,
    precioAnterior: null,
    badge: "nuevo",
    descripcion: "Carga rápida para dos dispositivos, formato ultra slim.",
    caracteristicas: ["20.000mAh real", "Carga rápida 22.5W", "Display LED", "USB-C + 2 USB"],
    rating: 4.8,
    reviews: 18,
    stock: 44,
    color: "from-teal-500/20 to-black",
    img: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: 16,
    nombre: "Hoodie Oversize Black",
    categoria: "Moda",
    precio: 28990,
    precioAnterior: null,
    badge: "nuevo",
    descripcion: "Algodón premium, corte oversize y bordado minimal.",
    caracteristicas: ["Algodón 320g", "Corte oversize", "Bordado relieve", "Ediciones limitadas"],
    rating: 4.9,
    reviews: 73,
    stock: 19,
    color: "from-zinc-800/40 to-black",
    img: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80"
  }
];

const CATEGORIAS = [
  { id: "tecnologia", nombre: "Tecnología", desc: "Gadgets y sonido", icon: "🎧" },
  { id: "gaming", nombre: "Gaming", desc: "Setup que rompe", icon: "🎮" },
  { id: "accesorios", nombre: "Accesorios", desc: "Carga, soportes y más", icon: "⚡" },
  { id: "moda", nombre: "Moda", desc: "Streetwear urbano", icon: "🧢" },
  { id: "tendencias", nombre: "Tendencias", desc: "Lo último que rompe", icon: "🔥" },
  { id: "hogar", nombre: "Hogar", desc: "Espacio con vibe", icon: "💡" },
  { id: "top", nombre: "Más vendidos", desc: "Los que la rompen", icon: "🏆" },
];

const FAQS = [
  { q: "¿Cómo compro?", a: "Elegís tu producto, lo agregás al carrito y completás tus datos en el checkout. También podés coordinar todo por WhatsApp." },
  { q: "¿Puedo comprar por WhatsApp?", a: "Sí, podés escribirnos en cualquier momento y coordinamos tu pedido sin complicaciones." },
  { q: "¿Hacen envíos?", a: "Hacemos envíos a domicilio y también podés retirar coordinando previamente. Los costos varían según la zona." },
  { q: "¿Puedo retirar mi pedido?", a: "Sí, coordinamos punto y horario por WhatsApp para que retires sin esperas." },
  { q: "¿Qué métodos de pago aceptan?", a: "Transferencia, pago al recibir, pago online y coordinación directa por WhatsApp." },
  { q: "¿Cómo sé si hay stock?", a: "En cada producto mostramos disponibilidad. Si tenés dudas, consultá antes de comprar para asegurarte." },
  { q: "¿Puedo cambiar un producto?", a: "Sí, dentro de los días estipulados en nuestras políticas y siempre que el producto esté sin uso." },
  { q: "¿Cuánto tarda la entrega?", a: "Los tiempos dependen de la zona, pero te avisamos en todo momento el estado del envío." },
];

window.__PAPU_DATA__ = { PRODUCTS, CATEGORIAS, FAQS };
